# Site settings
author: Steven Kumarsingh
title: Why did you decide to learn Software Engineering?
header-img: img/home-bg.png
email: stevenks17@gmail.com
copyright_name: Steven Kumarsingh
description: > # this means to ignore newlines until "baseurl:"
  From Computer Engineer to Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  stevenks17

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
